// <auto-generated />
using CeylanTurizm.Data.Concrete.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CeylanTurizm.Data.Migrations
{
    [DbContext(typeof(CeylanTurizmDbContext))]
    partial class CeylanTurizmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("CeylanTurizm.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusPlaque")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusSeatingCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDelte")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpedition")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityDescription2")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityDescription3")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityDescription4")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityDescription5")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Expedition", b =>
                {
                    b.Property<int>("ExpeditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpeditionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionFinish")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionHour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpeditionPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionStation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExpeditionId");

                    b.HasIndex("BusId");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.TicketSales", b =>
                {
                    b.Property<int>("TicketSalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("customerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("customerSurname")
                        .HasColumnType("TEXT");

                    b.Property<string>("customerTcNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("customerTelNo")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketSalesId");

                    b.HasIndex("ExpeditionId");

                    b.ToTable("TicketSales");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Expedition", b =>
                {
                    b.HasOne("CeylanTurizm.Entity.Bus", "Bus")
                        .WithMany("Expeditions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.TicketSales", b =>
                {
                    b.HasOne("CeylanTurizm.Entity.Expedition", "Expedition")
                        .WithMany("TicketSales")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Bus", b =>
                {
                    b.Navigation("Expeditions");
                });

            modelBuilder.Entity("CeylanTurizm.Entity.Expedition", b =>
                {
                    b.Navigation("TicketSales");
                });
#pragma warning restore 612, 618
        }
    }
}
